server:
  port: 8097
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://18.221.44.217:8086/eureka
  instance:
    preferIpAddress: true

spring:
  application:
    name: request-service
  jpa:
    hibernate:
      ddl-auto: none
    database: ORACLE
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
  datasource:
    url: jdbc:oracle:thin:@requestservice.cnqojmkjqy61.us-east-2.rds.amazonaws.com:1521:ORCL
    username: requestService
    password: requestService
    driver-class-name: oracle.jdbc.OracleDriver
    tomcat:
      max-active: 10
      max-idle: 10
      min-idle: 5
      min-evictable-idle-time-millis: 9000