server:
  port: 8103
  
spring:
  application:
    name: RESIDENT-COMPOSITE
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://192.168.61.123:8086/eureka