
spring:
    #Basic Data Access Set-up
    jpa:
        database-platform: org.hibernate.dialect.Oracle10gDialect
        hibernate:
            ddl-auto: update
        database: ORACLE
        show-sql: true
    #Datasource
    datasource:
        url: jdbc:oracle:thin:@unit-complex-db.c0hnpmmhpqu2.us-east-2.rds.amazonaws.com:1521:ORCL
        username: apartments
        password: Homes123
        driver-class-name: oracle.jdbc.OracleDriver
        tomcat:
            max-active: 10
            max-idle: 10
            min-idle: 5
            min-evictable-idle-time-millis: 9000    
        
    application:
        name: COMPLEX-SERVICE
        
    cloud:
        inetutils:
            ignored-interfaces:
                - docker0
                - veth.*
            preferred-networks:
                - 52.14.202.179
                - 18.221.44.217
                - 13.59.173.242

server:
    port: 8093

eureka:
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: http://18.221.44.217:8086/eureka