server:
  port: 8085
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8086/eureka

zuul:
  host:
    socket-timeout-millis: 10000    
  routes: 
    client:
      path: /**
      serviceId: CLIENT-SERVICE
      strip-prefix: false
    request:
      path: /api/request/**
      serviceId: REQUEST-SERVICE
    associate:
      path: /api/associates/**
      serviceId: ASSOCIATE-SERVICE
    complex:
      path: /api/complex/**
      serviceId: COMPLEX-SERVICE
    complex-composite:
      path: /api/complex-composite/**
      serviceId: COMPLEX-COMPOSITE
    request-composite:
      path: /api/request-composite/**
      serviceId: REQUEST-COMPOSITE
    resident-composite:
      path: /api/resident-composite/**
      serviceId: RESIDENT-COMPOSITE
    profile-composite:
      path: /api/profile-composite/**
      serviceId: PROFILE-COMPOSITE
    slack-service:
      path: /api/slack/**
      serviceId: SLACK-SERVICE
spring:
  application:
    name: zuul-server