server:
  port: ${service.port:9999}
  
spring:
  application:
    name: resident-composite
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}

