server:
  port: 8090
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8086/eureka
      
spring:
  application:
    name: associate-service
  jpa:
    hibernate:
      ddl-auto: none
    database: ORACLE
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
  datasource:
    url: jdbc:oracle:thin:@associatedb.cqa6zz8kqsxy.us-east-2.rds.amazonaws.com:1521:ORCL
    username: admin
    password: associatepass
    driver-class-name: oracle.jdbc.OracleDriver
    tomcat:
      max-active: 10
      max-idle: 10
      min-idle: 5
      min-evictable-idle-time-millis: 9000
